# See https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml as a reference.

skip-files:
  - "**/*.gen.go"
linters:
  enable-all: false
  disable-all: true

  # Please keep this list sorted alphabetically
  enable:
    - asasalint # checks for pass []any as any in variadic func(...any)
    - asciicheck # checks that your code does not contain non-ASCII identifiers
    - bidichk # checks for dangerous unicode character sequences
    - bodyclose # checks whether HTTP response body is closed successfully
    - copyloopvar # checks for pointers to enclosing loop variables
    - cyclop # checks function and package cyclomatic complexity
    - dupl # tool for code clone detection
    - errcheck # checking for unchecked errors, these unchecked errors can be critical bugs in some cases
    - errname # checks that sentinel errors are prefixed with the Err and error types are suffixed with the Error
    - errorlint # finds code that will cause problems with the error wrapping scheme introduced in Go 1.13
    - exportloopref # checks for pointers to enclosing loop variables
    - forbidigo # forbids identifiers
    - funlen # tool for detection of long functions
    - gochecknoglobals # checks that no global variables exist
    - gocognit # computes and checks the cognitive complexity of functions
    - goconst # finds repeated strings that could be replaced by a constant
    - gocritic # provides diagnostics that check for bugs, performance and style issues
    - gocyclo # computes and checks the cyclomatic complexity of functions
    - godot # checks if comments end in a period
    - goimports # in addition to fixing imports, goimports also formats your code in the same style as gofmt
    # deprecated, replaced with "mdn" # - gomnd # detects magic numbers
    # allowed # - gomoddirectives # manages the use of 'replace', 'retract', and 'excludes' directives in go.mod
    - gomodguard # allow and block lists linter for direct Go module dependencies. This is different from depguard where there are different block types for example version constraints and module recommendations
    - goprintffuncname # checks that printf-like functions are named with f at the end
    - gosec # inspects source code for security problems
    - gosimple # specializes in simplifying a code
    - govet # reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - ineffassign # detects when assignments to existing variables are not used
    - lll # reports long lines
    - loggercheck # checks key value pairs for common logger libraries (kitlog,klog,logr,zap)
    - makezero # finds slice declarations with non-zero initial length
    - mnd # detects magic numbers
    - nestif # reports deeply nested if statements
    - nilerr # finds the code that returns nil even if it checks that the error is not nil
    - nilnil # checks that there is no simultaneous return of nil error and an invalid value
    - nolintlint # reports ill-formed or insufficient nolint directives
    - reassign # checks that package variables are not reassigned
    - staticcheck # is a go vet on steroids, applying a ton of static analysis checks
    - stylecheck # is a replacement for golint
    - tenv # detects using os.Setenv instead of t.Setenv since Go1.17
    - tparallel # detects inappropriate usage of t.Parallel() method in your Go test codes
    - unused # checks for unused constants, variables, functions and types
    - usestdlibvars # detects the possibility to use variables/constants from the Go standard library
    # wastedassign is disabled because of generics.
    # You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649.
    # - wastedassign # finds wasted assignment statements
    - whitespace # detects leading and trailing whitespace
    - interfacebloat # checks the number of methods inside an interface

# Please keep this list sorted alphabetically
linters-settings:
  dupl:
    threshold: 200

  goimports:
    local-prefixes: git.xtools.tv

  gosec:
    excludes:
      - G115 # Potential integer overflow when converting between integer types

  govet:
    enable:
      - shadow

  funlen:
    lines: 100
    statements: -1

  lll:
    line-length: 150

  nestif: {}

  nolintlint:
    allow-no-explanation:
      - funlen
      - gocognit
      - lll
    require-explanation: true
    require-specific: true
